BalancerMaxis/multisig-ops

.github/workflows/merge_json_files.yaml, tools/python/merge_pr_jsons.py, tools/python/requirements.txt
- python script to merge jsons from each commit into batched files by multisig and week.
- Github actions to run it PRs are merged.
- Requires that the GITHUB_TOKEN has read and write repo access.
=> autobatch PR jsons

tools/python/brownie/helpers/addresses.py
=> Opti multisigs

.github/workflows/main.yml, .github/workflows/merge_json_files.yaml, .github/workflows/run_auth_gen.yaml, .github/workflows/run_feesweep.yaml, BIPs/00batched/authorizer/2023-02-12_gnosis.json
Tuned up the actions a bit to run less/use labels better, etc.
=> Update github actions

BIPs/BIP-208-209-210.json
Remove changes specified by BIP-210 from the combined BIP at request from Stargate(the original poster) who have decided not to continue with their migration.
=> Backout BIP-210 from combined BIP payload

BIPs/BIP-254.csv
- Airdrop for Beethoven-X worth $40k with BAL price at $7.19
=> BIP-254: Beethoven-X SP BAL airdrop

BIPs/BIP-255.json
* Grant roles for cron relayer (join / exit / swap)
* Simuation: https://dashboard.tenderly.co/public/safe/safe-apps/simulator/f19803e3-3508-4345-9572-47f23b9080c3
=> BIP-255: Grant roles for CRON relayer

BIPs/BIP-265-267.json
Adds Cron finance reth/wsteth CSP, COIL/USDC (50/50), USH/unshETH (80/20)
Simulation: https://dashboard.tenderly.co/public/safe/safe-apps/simulator/37c011b4-0974-483b-a313-9ed9e4e042f7
=> BIP-265-267 Add additional gauges

tools/python/helpers/monorepo-addresses.json
Will regen now and then until there is a way to easily generate from an action.
=> Add monorepo address book dated today from script run on monorepo fork

BIPs/BIP-272.json
- grant role to set swap fees on Arbitrum
- Tenderly simulation: https://dashboard.tenderly.co/public/safe/safe-apps/simulator/97a01a3f-d370-4cf0-bcbc-11fcd53de8d8
=> BIP-272: Weighted Pool v1 Permission Granting

.github/workflows/run_gauge_payload_report.yaml, action-scripts/brownie/scripts/get_gauge_mappings.py
Handle another exception (no abi in payload file)
throw an error if gauge is not init joined.
try using a different commit hash to see if they match
=> Little Fixes to gauge report

action-scripts/merge_pr_jsons.py
1. Walks through all dirs in `BIPs/` directory
2. Finds out what BIPs have `createdAt` within current week
3. Group them all by the chain and by msig address
4. In the end, collect all transactions from grouped BIPs and store to files in format `<chain_id>-<msig_addr>`
=> [feat] - implement json merging algorithm POC

action-scripts/merge_pr_jsons.py, action-scripts/requirements-actions.txt, action-scripts/tx_builder_templates/l2_checkpointer_gauge_add.json
Create another payload to run after the governance payload to add new L2 gauges to the mainnet checkpointer.
=> Generate L2 Checkpointer Payloads

action-scripts/merge_pr_jsons.py
=> Fix boolean logic around when to create a checkpointer payload

.github/workflows/run_gauge_payload_report_v2.yaml, action-scripts/brownie/scripts/report_gauge_add.py, action-scripts/brownie/scripts/report_gauges.py, action-scripts/brownie/scripts/script_utils.py
Add gauge removal functionality by using SC selectors check
=> feat: Gauge removals functionality

action-scripts/merge_pr_jsons.py
As requested, we need to validate each json that is being merged and make sure it has correct format and all data is present
Add validations for:
-  ChainId is specified and valid
- `createdFromSafeAddress` is present and is a correct string
- `createdFromSafeAddress` is listed in address book 
Fixes #275
=> feat: fail loud on BIP json validation

BIPs/2023-W25/BIP-341.json
- grant role to call votingescrow remapper
- call remapper to set local user Tetu veBAL locker with delegate Tetu mainnet multisig
- Tenderly sim: https://dashboard.tenderly.co/public/safe/safe-apps/simulator/51cadf10-5526-4e53-bba9-19b9dac88873
=> BIP-341: Set Escrow Re-mapper Manager for Tetu

.github/workflows/merge_json.yaml
Example PR generated with report: https://github.com/BalancerMaxis/multisig-ops/pull/301
Fixes #281
=> Automate report on merged json

BIPs/2023-W26/BIP-348.json
- transfer 93,750 USDC to OpCo's wallet for Onsite funding
- Tenderly sim: https://dashboard.tenderly.co/public/safe/safe-apps/simulator/5460470e-a661-4dc5-8ccc-aa5fced1550c
=> BIP-348: Ecosystem ONsite Proposal Q4 2023

BIPs/2023-W26/BIP-347.json
- send 132630 USDC
- send 25400 BAL
- ETH SEND NOT INCLUDED as this has to be done in a spearate tx!
- Tenderly sim: https://dashboard.tenderly.co/public/safe/safe-apps/simulator/1a042ceb-a959-4b25-93d5-fac02d3f649f
=> BIP-347: Fund Balancer Maxis for Q3 2023

action-scripts/brownie/scripts/report_gauges.py, action-scripts/brownie/scripts/script_utils.py
- Simplify the code by handling everything in one handler
- Add better logs
=> feat: add parsing transfers

action-scripts/brownie/scripts/report_gauges.py
Otherwise we have problems with new types transactions that are doing deposits
=> fix: skip transactions without contractInputsValues

tools/python/brownie/scripts/maxi_operations/bribe_ecosystems.py
1: Cowswap final USD directly injector
2: Send BAL to injector when placing the cowswap order.
=> Integrate veBalFeeInjector into fee redirection logic

action-scripts/brownie/scripts/validate_bip.py
Somehow this was throwing an error on some payloads before.  This both provides more details if an error is thrown, and also does more specific validation of the data.  (no rush to review/already merged into my action testing branch) #330
=> fix: Check chain exists and improve error message

BIPs/2023-W28/BIP-365A.json, BIPs/2023-W28/BIP-365A.report.txt, BIPs/2023-W30/BIP365B.json, BIPs/2023-W30/BIP365B.report.txt
Migration Add new gauges this week Part A Simulation: https://dashboard.tenderly.co/public/safe/safe-apps/simulator/a2505980-f89c-4a02-a8b6-dfef7ac1e6ae
Kill Gauges in Week 30 Part B: https://dashboard.tenderly.co/public/safe/safe-apps/simulator/1d4522f8-a6ed-4d65-b620-d8a1fef96c6d
=> BIP-365 Migrate Affected Composable Stable Pools Wave 1

BIPs/2023-W29/BIP-369-1.json, BIPs/2023-W29/BIP-369-137.json, BIPs/2023-W29/BIP-369-42161.json
BIP-369-1: grant role on Mainnet
- Tenderly-sim: https://dashboard.tenderly.co/public/safe/safe-apps/simulator/41a8945d-357a-48a8-b394-0621acf202c1
BIP-369-137: grant role on Polygon
- Tenderly sim: https://dashboard.tenderly.co/public/safe/safe-apps/simulator/5f27ff63-3648-4359-a6ef-3e1b79fea38b
BIP-369-42161: grant role on Arbitrum
- Tenderly-sim: https://dashboard.tenderly.co/public/safe/safe-apps/simulator/acce0a59-dac9-4f33-a6d1-9ba3ec64ffc8
=> BIP-369: Grant CSPv5 Swap Fee Permissions to Cowswap & 1inch Labs Solver

BIPs/2023-W29/BIP-367-1.json, BIPs/2023-W29/BIP-367-100.json, BIPs/2023-W29/BIP-367-1100.json, BIPs/2023-W29/BIP-367-137.json, BIPs/2023-W29/BIP-367-42161.json, BIPs/2023-W29/BIP367-10.json
Changes addresses respectively to swap 0x815d654E930E840D0E0Ee1B18FFc8Fb4ddA4c6B3 for 0xB5485e0F543eE6e01e221A57e58ED95268215Ac9 and 0x6bB4720473d4D7133f944785e5EE1A650C07f34e for 0xCae6f77a6cf4C952BF36793D91519fb4Ae86C264.
Simulations: 
Mainnet: https://dashboard.tenderly.co/public/safe/safe-apps/simulator/8e1bff81-9171-440d-a2ae-c28eab752990
Polygon: https://dashboard.tenderly.co/public/safe/safe-apps/simulator/dc89daca-47fd-4749-8d68-42b0f6f3088a
Arbitrum: https://dashboard.tenderly.co/public/safe/safe-apps/simulator/78033f8e-7ec1-4bcd-9b64-425e831e584f
Gnosis https://dashboard.tenderly.co/public/safe/safe-apps/simulator/de4bbeaa-a07e-4be0-9204-9ae3fe413300
Optimism https://dashboard.tenderly.co/public/safe/safe-apps/simulator/32931fdf-e1bc-4c1c-8b4f-0bdd52ef6ec8
zkEVM N/A
=> BIP-367-Update-Addresses-For-Emergency-Multisigs

action-scripts/merge_pr_jsons.py
Payload doesn't work.  Just need a list of addresses by chain that is accepted by tx builder (funny string lists in json)
=> Rework checkpointer output file to dump something useful

Bribs/partner_lm/gear/2023-09-18.json
https://docs.gearbox.finance/governance/setup/guards-multisigs https://etherscan.io/address/0x7b065Fcb0760dF0CEA8CFd144e08554F3CeA73D1
=> Return unbribed gear to Gearbox multisig

action-scripts/brownie/scripts/get_gauge_mappings.py, action-scripts/gen_add_permissions_payload.py, action-scripts/merge_pr_jsons.py, action-scripts/multi_merge_pr_jsons.py, action-scripts/requirements-actions.txt
separating the linting from pr #637 as per @Tritium-VLK's request [here](https://github.com/BalancerMaxis/multisig-ops/pull/637#pullrequestreview-1743377626)
i went ahead and linted the other two scripts too, and added `black` as a package requirement
=> chore: lint action scripts

tools/python/.env.template, tools/python/gen_vlaura_votes_for_epoch.py, tools/python/helpers/__init__.py, tools/python/requirements.txt
wip for #685 
current commit generates the following:
| blockchain   | pool_symbol             | pool_address                               |   protocol_fee_collected |     share |
|:-------------|:------------------------|:-------------------------------------------|-------------------------:|----------:|
| arbitrum     | rdnt/weth 80/20         | 0x32df62dc3aed2cd6224193052ce665dc18165841 |                  39092.3 | 0.234829  |
| ethereum     | bal/weth 80/20          | 0x5c6ee304399dbdb9c8ef030ab642b10820db8f56 |                  33472.9 | 0.201072  |
| ethereum     | b-reth-stable           | 0x1e19cf2d73a72ef1332c882f20534b6519be0276 |                  32871.7 | 0.197461  |
| ethereum     | gno/weth 80/20          | 0xf4c0dd9b82da36c07605df83c8a416f11724d88b |                  26214 …
=> feat: generate top 6 rev pools for given period

.github/workflows/run_reports_reusable.yaml
currently not building properly due to https://github.com/yaml/pyyaml/issues/724
see https://github.com/BalancerMaxis/multisig-ops/actions/runs/7615186728/job/20739112210?pr=746
=> ci: fix the python 3.10 env building

tools/python/aura_snapshot_voting/vote.py
- can you confirm your env has `web3==5.24.0`? im getting errors on using `to_checksum_address`. or am i missing something?
- no key error for me on calling `flatbook["multisigs/vote_incentive_recycling"]` 🤔 are we on the same version for `bal_addresses`? mine says `0.8.4`
- minor fix for generating `vote_txs/` dir if it doesnt exist yet
=> chore: minor hickups

action-scripts/brownie/networks.yaml, action-scripts/brownie/scripts/report_gauges.py
issue is that some of our contracts are not verified on snowtrace, eg https://snowtrace.io/token/0x72dD9b41FEc59cf58140cAb9C92CEfC8F212354D/contract/code?chainId=43114
made that more explicit in this fix. also if verified on snowtrace the report should pass instead of skip avax altogether
=> fix: snowtrace is online but not all contracts are verified

action-scripts/brownie/scripts/script_utils.py
See #853 for an example run, this branch was merged into that PR.
=> Additional logic to handle gyro rehype rate providers which are provided under different read functions.

.github/workflows/black.yaml, action-scripts/brownie/scripts/get_gauge_mappings.py, action-scripts/brownie/scripts/report_gauges.py, action-scripts/brownie/scripts/script_utils.py, tools/python/brownie/helpers/addresses.py, tools/python/brownie/scripts/maxi_operations/set_gas_station_watchlist.py, tools/python/mimicTestSweep.py
=> fix: better tenderly sim error handling

action-scripts/brownie/scripts/script_utils.py, action-scripts/brownie/scripts/validate_bip.py
this fixes the pool id retrieval for aura bribes:
=> feat: ameliorate hh report

action-scripts/brownie/scripts/report_gauges.py, action-scripts/brownie/scripts/script_utils.py
=> style: fix spacing in report

action-scripts/brownie/scripts/pokeInjectors.py
=> Disable github poker for zkevm

MaxiOps/brib_rebate_handling/05-2024/Bribe_Refund_May2024.md
Includes the two txns from May to request 3% refund from Hidden Hand to be sent to mainnet Maxi Multisig: eth:0xc38c5f97B34E175FFd35407fc91a937300E33860
=> Bribe_Refund_May2024

action-scripts/brownie/scripts/script_utils.py
closes #1033 #1034 
can be seen working in https://github.com/BalancerMaxis/multisig-ops/pull/1100
=> fix: remove suffix instead of strip

MaxiOps/Payroll_Txns/Q2_2024/USDC_June.json, MaxiOps/Payroll_Txns/Q2_2024/USDC_June.report.txt
- Pay Xeonus, Tritium, MikeB, Zen Dragon and gosuto for SP services for June 2024
- Pay Discord Anti-scam bot: $1000 as agreed upon with Danko. Costs were deducted from savings to have full discretionary budget available in Q3 after savings
- [Breakdown of costs](https://docs.google.com/spreadsheets/d/1ZyHkG4N_OGWQ98GK6dnOUHrPtvOMgtE5NbbnilGEvbs/edit?gid=829508970#gid=829508970)
- Freelancers will be paid once their hourly sheets for June are provided
=> Maxi Payroll: June 2024

action-scripts/brownie/networks.yaml, action-scripts/brownie/scripts/report_gauges.py, action-scripts/brownie/scripts/validate_bip.py
=> feat: add support for new chains

MaxiOps/auraBAL_vesters/July_2024_payroll_stkAuraBAL.json, MaxiOps/auraBAL_vesters/July_2024_payroll_stkAuraBAL.report.txt
Please reference this excel sheet for each persons designated vesting amount. Calculations are done proportionally per person monthly based on total BAL and total stkAuraBAL the safe received after converting. Note only Danko will get a unique amount at his request this month. Columns O - S https://docs.google.com/spreadsheets/d/1jN_ayUejTIPI_jiZfl86sVx6QzzWSBYHHM3T55nb3ok/edit?usp=sharing
Vesting contracts can be confirmed here: https://github.com/BalancerMaxis/bal_addresses/blob/7db7b8ab23ace23956aac0ca04eff68a4a50fbd8/extras/arbitrum.json#L55
Transaction is here: https://app.onchainden.com/safes/arb1:0x5891b90CE909d4c3540d640d2BdAAF3fD5157EAD/transactions/0x1dc2ca6c5b7fc60063fd0ac8a7c0f0575ab1020cdf667102b12845619ac88e1a?nid=376182
=> stkAuraBAL Vesters July 2024

.github/workflows/upkeeps.yaml, tools/python/query_upkeeps.py
the actions auto commits to a separate branch
raw csv file is then available at `https://raw.githubusercontent.com/BalancerMaxis/multisig-ops/upkeeps/upkeeps.csv`, which is auto imported here: https://docs.google.com/spreadsheets/d/1SAo0ZgJaAQ-1T1Hd5BIovVWKDwjBZrOzp0ox64h1rWI/
=> ci: query chainlink upkeeps and dump to csv every midnight utc

.github/workflows/post_aura_gauge_votes.yaml, MaxiOps/vlaura_voting/2024/W29/input/input.csv, tools/python/aura_snapshot_voting/requirements.txt, tools/python/aura_snapshot_voting/vote.py
https://docs.google.com/spreadsheets/d/1w63dyNGi0IB_bXgGXQk2lwknnT5wxCUkKHVp5bHqlFc/edit?gid=916207796#gid=916207796
=> 2024-W29 vote csv

MaxiOps/vlaura_voting/2024/W31/input/BD Vote Template - August 1 2024.csv, tools/python/aura_snapshot_voting/vote.py
=> Add voting data for 2024-W31

action-scripts/brownie/scripts/script_utils.py
reporting should not run for files removed, only added or modified
=> fix: ignore files removed from pr

.github/workflows/README.md
=> docs: warn about workflow environments

MaxiOps/Payroll_Txns/Q3_2024/USDC_August.json, MaxiOps/Payroll_Txns/Q3_2024/USDC_August.report.txt, MaxiOps/auraBAL_vesters/Q3-2024/September_2024.json, MaxiOps/auraBAL_vesters/Q3-2024/September_2024.report.txt
[Sheet](https://docs.google.com/spreadsheets/d/1jN_ayUejTIPI_jiZfl86sVx6QzzWSBYHHM3T55nb3ok/edit?usp=sharing) for reference
[Bal addresses](https://github.com/BalancerMaxis/bal_addresses/blob/4cebcb436926c7c0098563f7b562d40f13494b95/extras/arbitrum.json#L67) for vesters
=> Contributor salaries august 2024

MaxiOps/add_rewards/fraxtal/sFRAX-Pairs-FXS-from-AMO.json, MaxiOps/add_rewards/fraxtal/sFRAX-Pairs-FXS-from-AMO.report.txt
Pair/Child gauge:
sFRAX/sDAI 0x34E040bC0342EbBfBC7a6306EB1B8E6579185c94 sFRAX/sDAI/sUSDe 0x275e8514b83479f526673327B279753aBC666a05 sFRAX/sfrxETH 0x71c365fB739faFdba44B1564558849216de69958
AMO : 0xe9b3f9cd8851216fBb828da590CCA8CE7F03E863 (https://fraxscan.com/address/0xe9b3f9cd8851216fbb828da590cca8ce7f03e863#readContract)
FXS Address: 0xFc00000000000000000000000000000000000002
=> sFRAX-Pairs-FXS-from-AMO

BIPs/2024-W37/BIP-689 Claim stkAAVe from Linear Pools.json, BIPs/2024-W37/BIP-689 Claim stkAAVe from Linear Pools.report.txt
Proposal: https://forum.balancer.fi/t/bip-xxx-claim-stkaave-from-linear-pools/5973
Aave ARC:  https://governance.aave.com/t/arc-whitelist-balancer-s-liquidity-mining-claim/9724
=> BIP-689-Claim-stkAAVe-from-Linear-Pools

MaxiOps/Payroll_Txns/Q3_2024/USDC_September.json, MaxiOps/Payroll_Txns/Q3_2024/USDC_September.report.txt, MaxiOps/vlaura_voting/2024/W41/output/payload.json
- Contributor USDC salaries as per funding proposal Q3 2024
- [Budgeting tab](https://docs.google.com/spreadsheets/d/10J_m6A6iQGy86cZf_m0BJCfOWXsKU0q2_Ku6GSgJWk4/edit?gid=0#gid=0) as reference
=> Contributor Payroll: September 2024

MaxiOps/Payroll_Txns/Q3_2024/Freelancer_Discretionary_USDC_September_2024.json, MaxiOps/Payroll_Txns/Q3_2024/Freelancer_Discretionary_USDC_September_2024.report.txt
- [Cost breakdown](https://docs.google.com/spreadsheets/d/10J_m6A6iQGy86cZf_m0BJCfOWXsKU0q2_Ku6GSgJWk4/edit?gid=1937290596#gid=1937290596) sheet
- Added new payees in separate bal_addresses PR [here](https://github.com/BalancerMaxis/bal_addresses/pull/468)
=> Discretionary and Freelance Payroll: September 2024

MaxiOps/brib_rebate_handling/09-2024/Bribe_Refund_September2024.md
Bribe refund request for HH reference. Total of 8252.83 USDC Txns noted in the markdown file.
=> Bribe_Refund_September2024

tools/python/merkl.py
=> feat: basic logic for building a claim

.github/workflows/run_reports_reusable.yaml
eg see https://github.com/BalancerMaxis/multisig-ops/actions/runs/11558098792/job/32169665967
=> ci: continue workflow even if comment cannot be posted

MaxiOps/veMODE-Transactions/Vote-Transactions/veMODE-BPT-Vote-1.json, MaxiOps/veMODE-Transactions/Vote-Transactions/veMODE-BPT-Vote-1.report.txt
Voting with 100% of our BPT weight for the Balancer gauge. The gauge is equal to the multisig address in this scenario. 0x9ff471F9f98F42E5151C7855fD1b5aa906b1AF7e
=> veMODE-BPT-Vote-1

BIPs/2024-W44/[BIP-726] Adopt SEAL Whitehat Safe Harbor Agreement.json, BIPs/2024-W44/[BIP-726] Adopt SEAL Whitehat Safe Harbor Agreement.report.txt
per comment here: https://github.com/BalancerMaxis/multisig-ops/pull/1433#issuecomment-2443114022
=> fix: register safe harbor from dao msig

MaxiOps/Payroll_Txns/Q4_2024/Discretionary_Pay_Oct_2024.json, MaxiOps/Payroll_Txns/Q4_2024/Discretionary_Pay_Oct_2024.report.txt
Discretionary payments for:
- Injector v2 review
- Jalbrekt work hours
- Hyferion work hours
[Accounting](https://docs.google.com/spreadsheets/d/1caq7mui79pec-q-XvOiR2cnj2cnMOd3-eaIpiB9SIqE/edit?gid=1353364322#gid=1353364322) and [transaction log](https://docs.google.com/spreadsheets/d/1caq7mui79pec-q-XvOiR2cnj2cnMOd3-eaIpiB9SIqE/edit?gid=327957482#gid=327957482)
=> Discretionary Payments: October 2024

BIPs/4269-W69/test/BIP-344.json, BIPs/4269-W69/test/BIP-344.report.txt, MaxiOps/auraBAL_vesters/Q4-2024/stakingAuraBAL_and-3-Months-Payout.json, MaxiOps/auraBAL_vesters/Q4-2024/stakingAuraBAL_and-3-Months-Payout.report.txt, action-scripts/brownie/scripts/validate_bip.py
=> feat: skip bip specific checks for payloads outside of the bips directory

action-scripts/brownie/requirements-actions.txt
ref: https://github.com/safe-global/safe-eth-py/releases/tag/v6.0.0
=> ci: v6 introduces breaking changes for our imports

MaxiOps/vlaura_voting/2024/W51/input/BD Vote Template - December 5 2024.csv
Add voting data for 2024-W51
[BD Vote Sheet](https://docs.google.com/spreadsheets/d/1w63dyNGi0IB_bXgGXQk2lwknnT5wxCUkKHVp5bHqlFc/edit?gid=1363051255#gid=1363051255)
=> Add voting data for 2024-W51

BIPs/00batched/2024-W50/tg_template.txt
Fix gnosis DAO multisig safe (changed tg message posted in telegram as well)
=> Fix tg_template for 2024-w50 batch

MaxiOps/PoolParameterChanges/PoolAmpChanges/Mainnet/v3-AaveLidowstETHto5000-&-Ethx-aWETHto500.json, MaxiOps/PoolParameterChanges/PoolAmpChanges/Mainnet/v3-AaveLidowstETHto5000-&-Ethx-aWETHto500.report.txt
Matches old Lido wstETH-wETH pool and old ETHx-wstETH pool to compete for volumes.
=> v3-AaveLidowstETHto5000-&-Ethx-aWETHto500

MaxiOps/PoolParameterChanges/PoolAmpChanges/Arbitrum/sUSDX-USDX-Pools-&-SwapFee.json, MaxiOps/PoolParameterChanges/PoolAmpChanges/Arbitrum/sUSDX-USDX-Pools-&-SwapFee.report.txt
A factors set to 800 now that pool has 1M TVL in each at request of the USDX project team. Swap fee to 4 bps on sUSDX pool.
=> sUSDX-USDX-Pools-&-SwapFee

MaxiOps/add_rewards/ethereum/add-BAL-&-EUL-for-EUL-wETH-CowAMM.json, MaxiOps/add_rewards/ethereum/add-BAL-&-EUL-for-EUL-wETH-CowAMM.report.txt
Adds BAL with v1 injector as distributor and EUL with v2 injector as distributor.
=> add-BAL-&-EUL-for-EUL-wETH-CowAMM

tools/python/aura_snapshot_voting/vote.py
=> account for pending txs when calculating nonce when posting vlaura vote tx 

MaxiOps/Payroll_Txns/Q4_2024/Discretionary_Pay_Dec_2024.json, MaxiOps/Payroll_Txns/Q4_2024/Discretionary_Pay_Dec_2024.report.txt, MaxiOps/vlaura_voting/2025/W3/output/payload.json
- discretionary budget for hyferion and jalbrekt work hours
- over-hours budget for part-time engagement of gosuto
- Accounting [sheet](https://docs.google.com/spreadsheets/d/1caq7mui79pec-q-XvOiR2cnj2cnMOd3-eaIpiB9SIqE/edit?gid=929281495#gid=929281495)
=> Contributor Payroll: December 2024

BIPs/2025-W3/BIP-750 Balancer v3 Gauges Adds.report.txt, action-scripts/brownie/abis/IVaultV3Explorer.json, action-scripts/brownie/scripts/script_utils.py
closes #1572
i also added a .txt report for bip750 that ran with this change. note that the tokens column is now populated, proving the report is successful in retrieving v3 pool tokens
=> feat: query pool tokens from v3 vault if v2 fails

action-scripts/brownie/scripts/script_utils.py
=> fix: v3 vault is not deployed on all chains

MaxiOps/vlaura_voting/2025/W5/input/BD Vote Template - January 16 2025.csv
Add voting data for 2025-W5
[Sheet](https://docs.google.com/spreadsheets/d/1w63dyNGi0IB_bXgGXQk2lwknnT5wxCUkKHVp5bHqlFc/edit?gid=585112578#gid=585112578)
=> vlAURA voting

BIPs/2025/2025-W4/[BIP-763] Enable Boosted GHO 3pool on Balancer v3.json, BIPs/2025/2025-W4/[BIP-763] Enable Boosted GHO 3pool on Balancer v3.report.txt, BIPs/2025/2025-W5/[BIP-763] Enable Boosted GHO 3pool on Balancer v3 Kills.json, BIPs/2025/2025-W5/[BIP-763] Enable Boosted GHO 3pool on Balancer v3 Kills.report.txt
Proposal: https://forum.balancer.fi/t/bip-xxx-enable-boosted-gho-3pool-on-balancer-v3/6250
=> [BIP-763] Enable Boosted GHO 3pool on Balancer v3

action-scripts/brownie/scripts/script_utils.py
=> feat: get rate providers from v3 pools

MaxiOps/Emergency-Multisigs/Mainnet/enableRecoveryMode-TrenSTETH.json, MaxiOps/Emergency-Multisigs/Mainnet/enableRecoveryMode-TrenSTETH.report.txt
Per Mellows request to avoid any instance of an incorrect value in a rate provider.
=> enableRecoveryMode-TrenSTETH

action-scripts/brownie/scripts/reports.py, action-scripts/brownie/scripts/script_utils.py
closes #1714
bonus: also fixes an issue with not retrieving rate providers properly
=> fix: do not use hardcoded pool abis

MaxiOps/vlaura_voting/2025/W11/input/BD Vote Template - February 26 2025.csv
[Sheet](https://docs.google.com/spreadsheets/d/1w63dyNGi0IB_bXgGXQk2lwknnT5wxCUkKHVp5bHqlFc/edit?gid=1485379594#gid=1485379594)
=> Add voting data for 2025-W11

MaxiOps/vlaura_voting/2025/W11/output/payload.json, MaxiOps/vlaura_voting/2025/W11/output/report.txt, MaxiOps/vlaura_voting/2025/W11/output/vote_df.csv
for: https://github.com/BalancerMaxis/multisig-ops/pull/1801
```
{
"operation": 1,
"safeTxGas": 0,
"baseGas": 0,
"gasPrice": 0,
"gasToken": "0x0000000000000000000000000000000000000000",
"refundReceiver": "0x0000000000000000000000000000000000000000",
"to": "0xA65387F16B013cf2Af4605Ad8aA5ec25a2cbA3a2",
"data": "0x85a5affe00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000020e4ede35abdb10352b847718d49cdee966d7a7a8b2060d57a8aecc9b9594043f0",
"value": "0"
}
```
=> 2025-W11 vlaura voting report

MaxiOps/add_rewards/arbitrum/ARB-Grant-Injector-orbETH-&-eBTC.json, MaxiOps/add_rewards/arbitrum/ARB-Grant-Injector-orbETH-&-eBTC.report.txt
For these two pools: https://balancer.fi/pools/arbitrum/v3/0x2ece6781bace5e37386adef7a3d45d0bb05f8fce and https://balancer.fi/pools/arbitrum/v3/0x10f9e54aeea2fefa124238087dcfd919ba32f14d
=> ARB-Grant-Injector-orbETH-&-eBTC

MaxiOps/vlaura_voting/2025/W13/input/BD Vote Template - March 13 2025.csv
- [Sheet](https://docs.google.com/spreadsheets/d/1w63dyNGi0IB_bXgGXQk2lwknnT5wxCUkKHVp5bHqlFc/edit?gid=1694569822#gid=1694569822)
=> Add voting data for 2025-W13

.github/workflows/v3_fee_bot.yaml, action-scripts/abis/ProtocolFeeSweeper.json, action-scripts/requirements-actions.txt, action-scripts/v3_fee_bot.py
dry run, so the bot doesnt actually broadcast the calls to the sweeper yet
sample output:
```
checking for pending fees on sepolia:0x9c5c0bb79af59c0fb4624330eb3642eb2dbf8911 (DAI-USDC)...
checking for pending fees on sepolia:0x2766595b4fa4440d2edf5f987556673743b085fa (B-80VAULTX-20WETH)...
checking for pending fees on sepolia:0xc7512572bca89b90d604f88557d270716dcfea78 (Bv3-DAI-USDC-DirectionalFee)...
checking for pending fees on sepolia:0xaf4dd6e7a6dddb6df29b5425aeb4cf2c499aedbc (50USDC-50BALLISH)...
token: BAL 0xb19382073c7a0addbb56ac6af1808fa49e377b75
price: $1.4499999999999999555910790149937383830547332763671875
collectable in vault: 0.0015 BAL
sweepable in controller: 0 BAL
burning for: 0.002174999999999999933386618522 USDC
tx: {'chainId': 11155111,
'data': …
```
=> feat: v3 fee bot (dry run only)

action-scripts/merge_pr_jsons.py, tools/python/brownie/great_ape_safe/ape_api/balancer.py, tools/python/brownie/helpers/addresses.py, tools/python/brownie/scripts/csv_airdrop.py, tools/python/brownie/scripts/maxi_operations/bribe_ecosystems.py, tools/python/brownie/scripts/maxi_operations/bribe_txbuilder_with_rounds.py, tools/python/brownie/scripts/maxi_operations/flogFees.py, tools/python/claim_and_brib_gear.py, tools/python/helpers/hh_bribs.py, tools/python/standardize_poolRateCache.py, tools/python/sweepFeesNoJson.py
result of deprecating python 3.9
=> fix: dep stack now uses new style web3 syntax only

action-scripts/merge_pr_jsons.py
also see https://github.com/BalancerMaxis/multisig-ops/blob/b76434b70313b996f568849a401c18b88a978efe/action-scripts/brownie/scripts/validate_bip.py#L11-L38
=> fix: add missing address books for certain chains

MaxiOps/PoolParameterChanges/PoolStableSurgeParams/Mainnet/fwstETH-fWETH-New-2%T-5%M.json, MaxiOps/PoolParameterChanges/PoolStableSurgeParams/Mainnet/fwstETH-fWETH-New-2%T-5%M.report.txt
New Fluid wstETH-wETH pool with proper rate provider fee settings.
=> fwstETH-fWETH-New-2%T-5%M

.github/workflows/post_aura_gauge_votes.yaml
#1396 - already using indent=4, this will ensure files are being linted the same way
=> prettify json files from post aura guage votes action

MaxiOps/Payroll_Txns/Q1_2025/Discretionary_payroll_Q1_2025.json, MaxiOps/Payroll_Txns/Q1_2025/Discretionary_payroll_Q1_2025.report.txt
- Pay contributors for freelance work as per [sheet](https://docs.google.com/spreadsheets/d/1tnsG3E9id4xhlA0GLsiJEcM5lG3NzKQQMfvD6iTyaUA/edit?usp=sharing) - note: restricted to Balancer org e-mails
- Assuming rate of sUSDS <-> USDC of 1.0458
=> Discretionary Payroll Q1 2025

MaxiOps/vlaura_voting/2025/W17/input/BD Vote Template - April 10 2025.csv, tools/python/aura_snapshot_voting/review_votes.py
Add voting data for 2025-W17
https://docs.google.com/spreadsheets/d/1w63dyNGi0IB_bXgGXQk2lwknnT5wxCUkKHVp5bHqlFc/edit?gid=2079268910#gid=2079268910
=> vlAura-votes-2025-W17

MaxiOps/PoolParameterChanges/PoolStableSurgeParams/Mainnet/LoopFi-Surge-Params.json, MaxiOps/PoolParameterChanges/PoolStableSurgeParams/Mainnet/LoopFi-Surge-Params.report.txt
2 and 5% threshold or max fees as varies.
=> LoopFi-Surge-Params

MaxiOps/vlaura_voting/2025/W21/input/BD Vote Template - May 8 2025.csv
Add voting data for 2025-W21 [sheet](https://docs.google.com/spreadsheets/d/1w63dyNGi0IB_bXgGXQk2lwknnT5wxCUkKHVp5bHqlFc/edit?gid=1531156461#gid=1531156461)
=> Add voting data for 2025-W21

action-scripts/brownie/requirements-actions.txt, action-scripts/brownie/scripts/script_utils.py, tools/python/aura_snapshot_voting/requirements.txt, tools/python/aura_snapshot_voting/vote.py, tools/python/brownie/ape_safe.py
closes #1548
https://github.com/safe-global/safe-eth-py/releases/tag/v6.0.0
=> chore: update `safe-eth-py` to v6

.github/workflows/v3_fee_bot.yaml
- adjust fee bot to be manually triggerable but also being able to be called via workflows
- grant permissions to write on the protected branch
- Depends on https://github.com/BalancerMaxis/multisig-ops/pull/2213
=> Fee Bot: Adjustments for triggering

.github/workflows/schedule_v3_fee_bot.yaml
- Dispatch approach to trigger the fee bot
- Write perms needed to be able to execute the dispatch
=> Fee Bot: Workflow Dispatch Approach

action-scripts/brownie/scripts/reports.py
=> feat: flag faulty action ids

tools/python/aura_locker_harvesting/harvest_bribes.py
addresses: https://github.com/BalancerMaxis/multisig-ops/pull/2347#pullrequestreview-3143225458
=> claim paladin bribes on base

.github/workflows/run_reports_reusable.yaml
see https://github.com/BalancerMaxis/multisig-ops/pull/2353
=> fix: `networks.yaml` was deleted

action-scripts/brownie/scripts/script_utils.py
this is to prevent weird early exits such as https://github.com/BalancerMaxis/multisig-ops/actions/runs/17993835033/job/51189218143
=> feat: requests via session and automatically retry
