BalancerMaxis/multisig-ops

tools/python/brownie/helpers/addresses.py, tools/python/brownie/scripts/maxi_operations/set_gas_station_watchlist.py
- Add tritium as a deployer
- Add signers with no deployer wallet to watch lists with .25 ETH topup amount (total of 3 non-deployer signers after Tritium)
=> Give signers gas + make Trit deployer

tools/python/gen_add_permissions_payload.py
Simple change to allow target to be specified like task/contract, which then pulls the addresses from the outputs dir for the given task in the monorepo.
=> allow task/deployment style target specification

action-scripts/brownie/scripts/report_gauge_add.py, action-scripts/brownie/scripts/script_utils.py
Reports will now have additional header displaying all chains present in file's tx list like this:
```
File name: BIPs/2023-W24/BIP-328.json
COMMIT: `1a2b3c4d5e6f7g8h9i0j`
CHAIN(S): `zkevm`
```
=> feat: add chain headers to each file reported

action-scripts/gen_add_permissions_payload.py
Had an issue where the report missed adding a safe address to one of the payload files. Also added some todos about making deployment selection easier and providing better reporting
=> Don't finish Permissions payload generation  if all payloads don't have a safe.

action-scripts/brownie/scripts/report_gauges.py, action-scripts/brownie/scripts/script_utils.py, action-scripts/merge_pr_jsons.py
Parsing BIP number and tx id from original BIP file.
File name: BIPs/00batched/2023-W26/1-0x10A19e7eE7d7F8a52822f6817de8ea18204F2e4f.json
COMMIT: `1a2b3c4d5e6f7g8h9i0j`
CHAIN(S): `mainnet`
```
+----------+--------------+--------------------------+----------+--------------------------------------------+--------------------------------------------+-------------------------+---------+-------------------+
| function | token_symbol |      recipient_name      |  amount  |               token_address                |             recipient_address              |        raw_amount       |   bip   | transaction_index |
+----------+--------------+--------------------------+----------+--------------------------------------------+--------------------------------------------+-------------------------+-- …
```
=> feat: Parse bip number and transaction index

BIPs/2023-W36/BIP-422.json, BIPs/2023-W36/BIP-422.report.txt
Swaps permissions to be properly set.
setSwapFeePercentage 0x32725667b078898f78f53e59f45eb1837b34a9469dbe36f9270b674247b23abf is permitted to the LM Multisig 0x326A7778DB9B741Cb2acA0DE07b9402C7685dAc6.
enableRecoveryMode 0x8ceae9d0f076b4b0c529529f6bf11832835b93b533445c655b840015f7025e50 is permitted to the PoolRecoveryHelper 0x3b8cA519122CdD8efb272b0D3085453404B25bD0
=> Permissions Fix

action-scripts/merge_pr_jsons.py
prevent failure when the address in the json is not checksummed.
=> patch: checksum the multisig address before match in merge script.

.github/workflows/merge_json.yaml, .github/workflows/poke_injectors.yaml, .github/workflows/run_auth_gen.yaml, .github/workflows/run_reports_reusable.yaml
introduces caching for workflows that rely on `brownie`. prevents having to download all `solc` and `vyper` binaries at every run.
via https://github.com/brownie-mix/github-actions-mix/blob/0bfdd5fab8ece6ab13d757173c9e8f68501ee998/.github/workflows/main.yaml#L22-L28
=> ci: cache compilers for `brownie` actions

MaxiOps/brib_rebate_handling/Bribe_Refund_Debts_March2024.md
Explains the HH refund standard procedure and explains the net debt owed to Hidden Hand due to miscalculated refund amounts in December 2023 and January 2024. Both Daos agreed to pay off this debt with future refunds until the net value is covered. Then refunds will continue as intended.
=> HH_Rebates_and_Debt

.github/dependabot.yaml
some actions are starting to give deprecation warnings
=> ci: install dependabot for gh actions

config/protocol_fees_constants.json
Raise mins such that at least 1500 USD is required to place an incentive on the Aura market.
Authorized as per [BIP-457] with the reason that Aura would like us to try to help them reduce gas costs by avoiding small bribes. 
Simulations: https://docs.google.com/spreadsheets/d/1PDFqNzl_38Wprx38VJ-9vEc_1OUPGwjlzVLZSbm3M2s/edit#gid=2142384993
=> Raise Aura Vote Incentive min to 1500 USDC

config/protocol_fees_constants.json
Try to get a bit better aura distro on L2s.
See Aura BD chat for convo with Maha.  TL;DR We're ok like at 1000 until fees/gas pick up substantially.
=> lower min_aura_incentive to 1000

MaxiOps/chainlinkAutomation/migrate_injector_arb1_part1.json, MaxiOps/chainlinkAutomation/migrate_injector_arb1_part1.report.txt, MaxiOps/chainlinkAutomation/migrate_injector_arb1_part2.json, MaxiOps/chainlinkAutomation/migrate_injector_arb1_part2.report.txt
- part 1 (kyc msig):
- whitelists the new forwarder (see https://automation.chain.link/arbitrum/32362394734451035504199802047588354855838202363897445238253548040898877967375) as the 'keeper registry'
- transfer ownership on the injector to the lm omnichain msig
- part 2 (lm omni msig):
- accept ownership of the injector
part 2 will fail in sim until part 1 has been execd onchain
=> chore: migrate injector arb1

config/protocol_fees_constants.json
Spoke to @Xeonus about this.  Need min 40k aura for a vote, this should be more than enough.
Right now almost all the aura voting is going ot 1 pool on the L2s, and in some cases there is nowhere for it to go.
Dropping down to 800 should allow a lot more pools to get Aura votes on L2s, and will enable the whole STIP flywheel to work better/spin up smaller pools.
=> Reduce min aura vote to 800 for better handling on L2s and STIP action

MaxiOps/brib_rebate_handling/06-2024/Bribe_Refund_June2024.md, MaxiOps/brib_rebate_handling/07-2024/Bribe_Refund_July2024.md
Includes previous four fee rounds, two per month resulting in:
*Total bribe refund for July 2024: 13,174.70 USDC*  + *Total bribe refund for June 2024: 14,302.76 USDC* for a total amount across two months equal to 27,477.46 USDC.
=> HH-Bribe-Refunds-June&July-2024

.github/workflows/post_aura_gauge_votes.yaml
final automation step for #685, works by retrieving the path of csvs merged into any `input` folder in `'MaxiOps/vlaura_voting/`, parses the year/week from the path, then passes it into the voting script.
tested on fork:
[csv vote pr](https://github.com/jalbrekt85/multisig-ops/pull/24)
[action being automatically run](https://github.com/jalbrekt85/multisig-ops/actions/runs/10164789709)
=> automatically post votes on merged vote csv

config/protocol_fees_constants.json
Last round 768 USD DFX incentives resulted in 0.12% of the vlAURA vote.  Need 0.1 to not be filtered.  This should be safe for a little while.
Also do not redistribute aura if the pool alerady has at least 600 bucks in Aura incentives from other sources posted at the time of allocation.
=> Always pay at least 800 to Aura markets.

.github/workflows/process_every_payload.yaml, .github/workflows/run_reports_reusable.yaml
closes #1237 
merging this to `main` will require that going forward this repo has two environments defined: `internal` and `external`. the `external` one will need a protection rule set up of "required reviewers":
=> ci: run internal and external prs in different envs

.github/workflows/run_reports_reusable.yaml, .gitignore
this should solve the issue of prs opened by actions instead of actual users to be recognised as external prs
=> ci: leverage fork var instead of repo names

.github/workflows/review_aura_gauge_votes.yaml, tools/python/aura_snapshot_voting/requirements.txt, tools/python/aura_snapshot_voting/review_votes.py
the workflow creates a report comment on a pr that is triggered when a csv is commited into `MaxiOps/vlaura_voting/**/input/*.csv`
checks that the allocation adds up to 100% and that each gauge address has a corresponding snapshot vote choice
see [here](https://github.com/jalbrekt85/multisig-ops/pull/34#issuecomment-2313343487) for an example of what the report comment looks like
=> validate vlaura vote csv

MaxiOps/brib_rebate_handling/08-2024/Bribe_Refund_August2024.md
Takes consideration of the 3 fee rounds transaction that occurred in August 2024.
Total refund amount: 15932.41 USDC
=> HH_Bribe_Refund_August_2024

MaxiOps/PoolParameterChanges/PoolSwapFeeChanges/Mainnet/tETH-wstETH-3bps-to-5bps.json, MaxiOps/PoolParameterChanges/PoolSwapFeeChanges/Mainnet/tETH-wstETH-3bps-to-5bps.report.txt
Moving fee from 3 bps to 5 bps at request to match Curve pool from Treehouse ETH team.
=> tETH-wstETH-3bps-to-5bps

MaxiOps/injectorScheduling/zkevm/set_poker_as_keeper.json, MaxiOps/injectorScheduling/zkevm/set_poker_as_keeper.report.txt, action-scripts/brownie/scripts/pokeInjectors.py
closes #1333 
this will allow us to remove it from defender and thus have all non chainlink keepers in one place
no active schedules on either injector, so no issues with missing a cycle
=> ci: enable poker on zkevm

MaxiOps/brib_rebate_handling/10-2024/Bribe_Refund_October2024.md, MaxiOps/brib_rebate_handling/11-2204/Bribe_Refund_November2024.md
Details all in md file.
October net: 8652.83 USDC
November net: 12586.00 USDC
Total of both: 21238.83 USDC
=> HH Refund for October and November

action-scripts/brownie/scripts/script_utils.py
- ad interim fix so reports run for v2 vault related payloads
- needs long term solution on how we distinguish between v2 and v3 vault related payloads
=> FIX: unique filter for v2 vault for action scripts

tools/python/paladin_claiming/recycle_bribes.py
paladin recently migrated their arbitrum distributor from v1 to v2 so some bribes are on the v1 contract and others on v2. the recycling script was previously hardcoding to use the v1 contract. this means we are missing out on the v2 bribes. this pr updates the script to dynamically claim from the distributor contract that the rewards are on based from the api so all available bribes are claimed
=> hotfix: dynamically choose paladin distributor contract

MaxiOps/PoolParameterChanges/v3-global-fees-gnosis.json, MaxiOps/PoolParameterChanges/v3-global-fees-gnosis.report.txt, MaxiOps/PoolParameterChanges/v3-global-fees.json, MaxiOps/PoolParameterChanges/v3-global-fees.report.txt
as per [bip734](https://forum.balancer.fi/t/bip-734-balancer-v3-launch-and-protocol-enhancements/6168)
=> chore: add v3 global fees payload json

MaxiOps/injectorScheduling/mainnet/GEAR_minWaitPeriod_Update_518400.json, MaxiOps/injectorScheduling/mainnet/GEAR_minWaitPeriod_Update_518400.report.txt
To fix injections for cow pool set minWaitPeriod to 7 days or less. Currently too high causing a delay.
=> GEAR_minWaitPeriod_Update_518400

MaxiOps/injectorScheduling/mainnet/wstETH-Transfer&InjectorSchedule-Lido-wstETH-wETH.json, MaxiOps/injectorScheduling/mainnet/wstETH-Transfer&InjectorSchedule-Lido-wstETH-wETH.report.txt
Per Lidos request distribute 3.71 wstETH over 4 weeks. Equal to 0.9275 wstETH per week starting ASAP. This TXN will start streaming upon execution. The injector and keeper will be funded upon execution.
=> wstETH-Transfer&InjectorSchedule-Lido-wstETH-wETH

action-scripts/brownie/scripts/script_utils.py
proof is in the pudding; #1656 
all gauges come back as preferential now
=> fix: pool id fallback is pool address

MaxiOps/CCTP_Bridge/send/USDC-Arbitrum-Base-v3-Bootstrapping-1.json, MaxiOps/CCTP_Bridge/send/USDC-Arbitrum-Base-v3-Bootstrapping-1.report.txt
Bridging 30000 USDC to Arbitrum and 15000 USDC to Base for initial bootstrapping of launch pools on each network.
Will follow this [notion](https://www.notion.so/18de395e22818014b713e5e5f35095a4?v=18de395e228180f7ae12000cf007f5da) page with flexibility for new partners arising.
Due to size of funds being bridged, this payload will not be loaded until review and approved by team members.
=> USDC-Arbitrum-Base-v3-Bootstrapping-1

MaxiOps/PoolParameterChanges/PoolStableSurgeParams/Arbitrum/StableSurge-LaunchPools-Config.json, MaxiOps/PoolParameterChanges/PoolStableSurgeParams/Arbitrum/StableSurge-LaunchPools-Config.report.txt, MaxiOps/PoolParameterChanges/PoolStableSurgeParams/Base/aGHO-aUSDC-MaxFee-Threshold-Update.json, MaxiOps/PoolParameterChanges/PoolStableSurgeParams/Base/aGHO-aUSDC-MaxFee-Threshold-Update.report.txt, MaxiOps/PoolParameterChanges/PoolStableSurgeParams/Mainnet/StableSurge-LaunchPools-config.json, MaxiOps/PoolParameterChanges/PoolStableSurgeParams/Mainnet/StableSurge-LaunchPools-config.report.txt
Initial launch used for testing different pools with 5% or 10% for maxSurgeFee and maxThreshold depending on asset type.
3pools typically should have smaller thresholds due to less room to go off peg. 50% vs 33% for parity require different threshold settings. 5% typically for 3pools. 5-10% being tested for 2pools. 
Max fee settings of 5 and 10% being utilized. Potentially both are too aggressive but we will see if they create to much friction or perform well. Can see potential for lower amounts such as 10 - 100x the baseFee making more sense. This would range from 0.05-4% in most cases as 0.005-0.04 are typical are stable pools.
=> StableSurge-LaunchPools-config

MaxiOps/signers/dao-sonic.json, MaxiOps/signers/dao-sonic.report.txt
dao msig on sonic still has default signers and low threshold (2/n)
this payload sets signers on par with dao msig on ethereum and raises threshold to 6/n
=> chore: add payload for sonic dao msig setup

MaxiOps/injectorScheduling/arbitrum/Arbitrum-USDC-Grant-Schedule-Week2.json, MaxiOps/injectorScheduling/arbitrum/Arbitrum-USDC-Grant-Schedule-Week2.report.txt
- Execute week 2 incentives as per [notion](https://www.notion.so/18de395e22818014b713e5e5f35095a4?v=18de395e228180f7ae12000cf007f5da)
- align incentives on existing pools and new ECLPs at 5PM CET 20.03.2025
eBTC v3 pools will reduce to 1850 USDC a week
New ECLPs will get 2500 USDC a week
We decided with @Zen-Maxi to only configure for 1 week and reconfigure a new longer schedule thereafter.
=> Arbitrum USDC Grant - Week 2 incentive Plan

tools/python/aura_snapshot_voting/requirements.txt, tools/python/aura_snapshot_voting/vote.py
the dep changes in #1860 that were needed to get the reporting automation to work broke the posting part. pinning `eth-account` seems to get both working now
also needs to use new [`key`](https://eth-account.readthedocs.io/en/stable/eth_account.signers.html#eth_account.signers.local.LocalAccount.key) attribute
=> aura voting: add eth-account

tools/python/requirements.txt
here is the dep tree that comes with bal addresses:
```
aiohappyeyeballs==2.6.1; python_version >= '3.9'
aiohttp==3.11.0b0; python_version >= '3.9'
aiosignal==1.3.1; python_version >= '3.7'
annotated-types==0.7.0; python_version >= '3.8'
anyio==4.9.0; python_version >= '3.9'
asttokens==2.4.1
async-timeout==4.0.3; python_version >= '3.7'
attrs==23.2.0; python_version >= '3.7'
backoff==2.2.1; python_version >= '3.7' and python_version < '4.0'
bal-tools @ git+https://github.com/BalancerMaxis/bal_tools.git@1ceff1066ff4aa22afc9fe3d89fc4e02032e2d06
bitarray==2.9.2
black==24.2.0; python_version >= '3.8'
cbor2==5.6.2; python_version >= '3.8'
cchecksum==0.0.7; python_version >= '3.8' and python_version < '4'
certifi==2024.2.2; python_version >= '3.6'
charset-normalizer==3.3.2; python_full_version …
```
=> ci: remove redundant deps

MaxiOps/PoolParameterChanges/PoolSwapFeeChanges/Base/GHO-v3-pool-changes-2025_04_03.json, MaxiOps/PoolParameterChanges/PoolSwapFeeChanges/Base/GHO-v3-pool-changes-2025_04_03.report.txt
As per MG request:
- Adjust GHO-USDC to 0.02%
- Adjust GHO-EURC to 0.01%
- Adjust GHO-USR stablesurge to 0.02%
=> Adjust GHO Swap Fees on v3 Pools on Base

MaxiOps/PoolParameterChanges/PoolRateParameterChanges/Gnosis/GBPeSDAI-stEUREURe-setRateCache-to-1.json, MaxiOps/PoolParameterChanges/PoolRateParameterChanges/Gnosis/GBPeSDAI-stEUREURe-setRateCache-to-1.report.txt
GBPe-sDAI: 0x9d93f38b75b376acdfe607cd1ecf4495e047deff
stEUR-EURe: 0x06135a9ae830476d3a941bae9010b63732a055f4
Each token that has a rate provider is set to 1, note that for stEUR-EURe only stEUR has a rate provider configured, so we only set that one
The first pool in the request has been set already
=> Set Rate Cache to 1 for additional Gnosis pools

MaxiOps/vlaura_voting/2025/W19/output/payload.json, MaxiOps/vlaura_voting/2025/W19/output/report.txt, MaxiOps/vlaura_voting/2025/W19/output/vote_df.csv
result from running: `tools/python/aura_snapshot_voting/vote.py --week-string 2025-W19` with hardcoded timestamp of `1745693358 ` and commenting out the `post_safe_tx` call
=> vlaura vote report for 2025-W19

MaxiOps/PoolParameterChanges/PoolStableSurgeParams/Base/USR-USDC-GHO-SurgeUpdate-30Percent.json, MaxiOps/PoolParameterChanges/PoolStableSurgeParams/Base/USR-USDC-GHO-SurgeUpdate-30Percent.report.txt, MaxiOps/vlaura_voting/2025/W21/output/payload.json
- As per MG request, new surge threshold percentage params from 10 to 30% to facilitate big trades with lower slippage
=> Update Surge Threshold to 30% for USR and USDC - GHO pools on Base

config/alliance_fee_share.json
- [Proposal](https://snapshot.box/#/s:balancer.eth/proposal/0x212dcd5b0e698c52bb9ae9c09d928d91850628b7ed636ecba30d3cdc6350b826)
- Currently only the v2 pool is eligible
- V3 pools didn't hit 5mln threshold yet, nor did Lido place voting incentives
I also created https://github.com/BalancerMaxis/multisig-ops/issues/2078 to address automatic verification if the pool list is indeed correct based on the Alliance param set
=> Balancer Alliance: Add eligible Lido pools

MaxiOps/add_rewards/ethereum/add-RZR-to-weETH-lstRZR-gauge.json, MaxiOps/add_rewards/ethereum/add-RZR-to-weETH-lstRZR-gauge.report.txt
The Maxi Multisig 0x9ff471F9f98F42E5151C7855fD1b5aa906b1AF7e will interact with the following gauges: Add Reward:
Target (Gauge Address): 0x320216774426b2765c72ab1ea9606d1474adf677 To (Authorizer Adaptor Entrypoint): 0xf5dECDB1f3d1ee384908Fbe16D2F0348AE43a9eA
Target (Gauge Address): 0x69bd054863dbf43a42189665dbd4060d2c07a2c8 To (Authorizer Adaptor Entrypoint): 0xf5dECDB1f3d1ee384908Fbe16D2F0348AE43a9eA
Reward Token: 0xb4444468e444f89e1c2cac2f1d3ee7e336cbd1f5 Distributor Address: 0xe2e45c8747133d32adb732ababcf25d800a8513d
Payload was made using the https://balancer.defilytica.tools/payload-builder/add-reward-to-gauge script
Pools
- RZR/weETH - https://balancer.fi/pools/ethereum/v3/0x3f89f8c0e0ffdfae0b97959303831fa893f1cfe0
- RZR/lstRZR - …
=> Add RZR to the lstRZR and weETH balancer pools on ETH Mainnet

config/alliance_fee_share.json
#2373 - adds the two starting quantamm pools. since these are the first pools being added, their fee split will be used as the default
=> add quantamm pools to partner config
